costs:
  http_trick:
    http_trick: 0.0
    split: 2.0
    disorder: 3.0
    fake: 5.0
    syndata: 6.0
    faked_split: 5.0
    seqovl: 6.0
    ipfrag: 7.0
    wsize: 8.0
    hostfake: 3.0
    oob: 8.0
    udp_len: 9.0
    ipv6_ext: 9.0

  split:
    http_trick: 2.0
    split: 0.0
    disorder: 1.0
    fake: 4.0
    syndata: 5.0
    faked_split: 2.0
    seqovl: 2.0
    ipfrag: 5.0
    wsize: 6.0
    hostfake: 4.0
    oob: 7.0
    udp_len: 9.0
    ipv6_ext: 8.0

  disorder:
    http_trick: 3.0
    split: 1.0
    disorder: 0.0
    fake: 4.0
    syndata: 5.0
    faked_split: 2.0
    seqovl: 2.0
    ipfrag: 5.0
    wsize: 6.0
    hostfake: 4.0
    oob: 7.0
    udp_len: 9.0
    ipv6_ext: 8.0

  fake:
    http_trick: 5.0
    split: 4.0
    disorder: 4.0
    fake: 0.0
    rst: 1.0
    syndata: 2.0
    faked_split: 1.0
    seqovl: 4.0
    ipfrag: 5.0
    wsize: 6.0
    hostfake: 5.0
    oob: 6.0
    udp_len: 3.0
    ipv6_ext: 7.0

  rst:
    http_trick: 5.0
    split: 4.0
    disorder: 4.0
    fake: 1.0
    rst: 0.0
    syndata: 2.0
    faked_split: 2.0
    seqovl: 4.0
    ipfrag: 5.0
    wsize: 6.0
    hostfake: 5.0
    oob: 6.0
    udp_len: 4.0
    ipv6_ext: 7.0

  syndata:
    http_trick: 6.0
    split: 5.0
    disorder: 5.0
    fake: 2.0
    syndata: 0.0
    faked_split: 2.0
    seqovl: 4.0
    ipfrag: 5.0
    wsize: 7.0
    hostfake: 6.0
    oob: 6.0
    udp_len: 4.0
    ipv6_ext: 7.0

  faked_split:
    http_trick: 5.0
    split: 2.0
    disorder: 2.0
    fake: 1.0
    syndata: 2.0
    faked_split: 0.0
    seqovl: 3.0
    ipfrag: 5.0
    wsize: 6.0
    hostfake: 5.0
    oob: 6.0
    udp_len: 5.0
    ipv6_ext: 7.0

  seqovl:
    http_trick: 6.0
    split: 2.0
    disorder: 2.0
    fake: 4.0
    syndata: 4.0
    faked_split: 3.0
    seqovl: 0.0
    ipfrag: 4.0
    wsize: 6.0
    hostfake: 6.0
    oob: 6.0
    udp_len: 7.0
    ipv6_ext: 7.0

  ipfrag:
    http_trick: 7.0
    split: 5.0
    disorder: 5.0
    fake: 5.0
    syndata: 5.0
    faked_split: 5.0
    seqovl: 4.0
    ipfrag: 0.0
    wsize: 5.0
    hostfake: 7.0
    oob: 5.0
    udp_len: 3.0
    ipv6_ext: 2.0

  wsize:
    http_trick: 8.0
    split: 6.0
    disorder: 6.0
    fake: 6.0
    syndata: 7.0
    faked_split: 6.0
    seqovl: 6.0
    ipfrag: 5.0
    wsize: 0.0
    hostfake: 8.0
    oob: 6.0
    udp_len: 6.0
    ipv6_ext: 6.0

  hostfake:
    http_trick: 3.0
    split: 4.0
    disorder: 4.0
    fake: 5.0
    syndata: 6.0
    faked_split: 5.0
    seqovl: 6.0
    ipfrag: 7.0
    wsize: 8.0
    hostfake: 0.0
    oob: 8.0
    udp_len: 9.0
    ipv6_ext: 9.0

  oob:
    http_trick: 8.0
    split: 7.0
    disorder: 7.0
    fake: 6.0
    syndata: 6.0
    faked_split: 6.0
    seqovl: 6.0
    ipfrag: 5.0
    wsize: 6.0
    hostfake: 8.0
    oob: 0.0
    udp_len: 5.0
    ipv6_ext: 6.0

  udp_len:
    http_trick: 9.0
    split: 9.0
    disorder: 9.0
    fake: 3.0
    syndata: 4.0
    faked_split: 5.0
    seqovl: 7.0
    ipfrag: 3.0
    wsize: 6.0
    hostfake: 9.0
    oob: 5.0
    udp_len: 0.0
    ipv6_ext: 4.0

  ipv6_ext:
    http_trick: 9.0
    split: 8.0
    disorder: 8.0
    fake: 7.0
    syndata: 7.0
    faked_split: 7.0
    seqovl: 7.0
    ipfrag: 2.0
    wsize: 6.0
    hostfake: 9.0
    oob: 6.0
    udp_len: 4.0
    ipv6_ext: 0.0
